### ISSUE TITLE
Support Elasticsearch 5.x

### ISSUE THREAD

**Issue by mjacksonw** [aptible/docker-elasticsearch#25]
Now that the "Elastic Stack" has all components (namely Kibana) released together, getting to 5.x on Elasticsearch is probably becoming increasingly important.

**Comment by krallin** [comment]
Thanks @mjacksonw. We've actually started investigating this on our end. 

Although the work on this image itself is mostly done (though I didn't push it to a PR), there's a bit of platform work to do before we can release this, namely the platform needs to tell container what their size is (Elastic 5.0 wants to allocate all memory upfront, and defaults to 2GB, which is too big for our default 1GB containers).

**Comment by zharben** [comment]
@krallin @mjacksonw +1 on this!  Specifically, the new ingest capabilities (basically, porting/inlining logstash filters) will make it much easier for us to properly index log event attributes (e.g. extract attributes from log messages, especially structured logs)

**Comment by krallin** [comment]
This is being worked on here: https://github.com/aptible/docker-elasticsearch/pull/26

**Comment by krallin** [comment]
This was released earlier today; just let us know if you hit any issues.

Cheers,
