### ISSUE TITLE
Upgrade to 1.4.4

### ISSUE THREAD

**Issue by fancyremarker** [aptible/docker-elasticsearch#4]
cc: @tobalsgithub

**Comment by tobalsgithub** [comment]
Anything I can do to help from my side?

**Comment by fancyremarker** [comment]
Hey @tobalsgithub: The checklist here is basically:

* [ ] Update the Dockerfile here (should be trivial)
* [ ] Test that the current aptible/docker-kibana image works with the updated Elasticsearch (some changes, especially [this one](https://gist.github.com/rmoff/379e6ce46eb128110f38) may be necessary)
* [ ] Optionally, update aptible/docker-kibana to Kibana 4 (again testing that it works with the updated Elasticsearch)

**Comment by fancyremarker** [comment]
Closing, since we skipped over 1.4.4 and upgraded to 1.5.2
